### ISSUE TITLE
Mention interval type theory

### ISSUE THREAD

**Issue by clayrat** [abooij/wiwikwlhott#4]
I.e.,
https://valis.github.io/doc.pdf
http://drops.dagstuhl.de/opus/volltexte/2017/7714/pdf/LIPIcs-FSCD-2017-28.pdf

and implementations:
https://github.com/valis/hoq
https://github.com/valis/vclang

**Comment by abooij** [comment]
Thanks for the suggestion.

Is there a bit more information about this? Is the work you linked in the process of being published? What is the relation between the first two links you posted (Isaev and Orton&Pitts)? Is there documentation for the implementation?

**Comment by abooij** [comment]
Inactive; closing.
